CREATE TABLE DATAACCESSPROFILE(
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TARGETCLASS VARCHAR(1023) NOT NULL,
    TARGETMETHOD VARCHAR(63) NOT NULL,
    PROCESSSTARTED TIMESTAMP NOT NULL,
    PROCESSFINISHED TIMESTAMP NOT NULL,
    RECORDED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    VERSION INTEGER NOT NULL
);
