CREATE TABLE JSF_DEMO_USER(
    NAME CHAR(7) PRIMARY KEY,
    FULLNAME VARCHAR(50) NOT NULL,
    USER_GROUP VARCHAR(32) NOT NULL,
    PASSWORD CHAR(44) NOT NULL,
    PASSWORD_HISTORY_1 CHAR(44) NOT NULL,
    PASSWORD_HISTORY_2 CHAR(44) NOT NULL,
    CONSECUTIVE_LOGIN_FAILURE INT NOT NULL,
    EXPIRATION DATE NOT NULL,
    UPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP
);
